import type { CategorySchema } from '@/lib/spec/fields';
import { parseCount, parseLining, parseStitchPattern, parseThreadMaterial, parseZipper, parseColor } from '@/lib/spec/parsers';
import type { SmallGoodsAttributes } from '@/lib/types';
import {
  dimensionsField,
  embossingFields,
  leatherEdgeField,
  leatherField,
  stitchingMethodField,
  threadColorField,
} from './common';

const cards = (text: string) => parseCount(text, 'kartu|card');
const WALLETS = ['FLAT_CARD_HOLDER', 'PATTERNED_CARD_HOLDER', 'BIFOLD_WALLET', 'TRIFOLD_WALLET', 'ACCORDION_WALLET', 'ZIP_AROUND_LONG_WALLET'] as const;
const hasZip = (a: SmallGoodsAttributes, c: string) => c === 'ZIP_AROUND_LONG_WALLET' || a.coin_zip_pocket;

export const SMALL_GOODS: CategorySchema<'SMALL_GOODS'> = {
  id: 'SMALL_GOODS',
  label: 'Wallets & small goods',
  label_id: 'Dompet & small goods',
  noun: 'small leather good (wallet / card holder)',
  scope: 'Wallets, card holders, passport covers, key pouches and other small leather goods.',
  detect: /dompet|wallet|card ?holder|kartu|passport|paspor|key ?(pouch|holder)|gantungan kunci/i,
  material_field: 'exterior_leather',
  material_label: 'Leather',
  constructions: [
    {
      id: 'ZIP_AROUND_LONG_WALLET',
      label: 'Zip-around long wallet',
      detect: /(sleting|zip|resleting)[^.]{0,30}(melingkar|around|keliling)|zip[\s-]?around|dompet panjang.{0,30}(sleting|zip)/i,
      vision_cue: 'Long rectangular wallet closed by a zipper running around three sides; interior card slots and often a coin zip pocket.',
      defaults: { dimensions_cm: { length: 20, width: 2.5, height: 10 }, front_slots: 6, back_slots: 6, cash_compartments: 2, coin_zip_pocket: true },
      labor_factor: 1.6,
    },
    {
      id: 'PATTERNED_CARD_HOLDER',
      label: 'Patterned / engraved card holder',
      detect: /(kartu|card).{0,40}(motif|batik|ukir|engrav|ornamen|pattern)|(motif|batik|ukir|engrav|ornamen).{0,40}(kartu|card)/i,
      vision_cue: 'Flat card holder whose outer face carries a carved, stamped or laser-engraved pattern or artwork.',
      defaults: { dimensions_cm: { length: 10, width: 0.6, height: 7 }, front_slots: 2, back_slots: 2, central_pockets: 1 },
      labor_factor: 0.6,
    },
    {
      id: 'FLAT_CARD_HOLDER',
      label: 'Flat card holder (single panel, no fold)',
      detect: /dompet kartu|card ?holder|card ?sleeve|card ?case|kartu pipih|pipih|slim wallet/i,
      vision_cue:
        'A SINGLE FLAT panel/sleeve with card slots visible on the front (and/or back) face. There is NO center fold line and it does not open like a book. Cards slide in from the top edge. Often a central pocket for folded cash.',
      defaults: { dimensions_cm: { length: 10, width: 0.4, height: 7 }, front_slots: 2, back_slots: 2, central_pockets: 1 },
      labor_factor: 0.5,
    },
    {
      id: 'TRIFOLD_WALLET',
      label: 'Trifold wallet',
      detect: /tri[\s-]?fold|lipat tiga/i,
      vision_cue: 'Wallet that folds twice into three panels; visibly thicker than a bifold, with two fold lines.',
      defaults: { dimensions_cm: { length: 10, width: 2.5, height: 9 }, front_slots: 3, back_slots: 3, cash_compartments: 1, id_window: true },
      labor_factor: 1.2,
    },
    {
      id: 'ACCORDION_WALLET',
      label: 'Accordion wallet',
      detect: /accordion|akordeon|harmonika|z[\s-]?fold/i,
      vision_cue: 'Wallet with a Z-folded pleated gusset that expands like an accordion, with stacked card pockets.',
      defaults: { dimensions_cm: { length: 11, width: 3, height: 8 }, front_slots: 4, back_slots: 4, cash_compartments: 1 },
      labor_factor: 1.2,
    },
    {
      id: 'BIFOLD_WALLET',
      label: 'Bifold wallet',
      detect: /bi[\s-]?fold|lipat dua|dompet lipat/i,
      vision_cue: 'Wallet that folds ONCE along a center spine like a book; two halves each holding card slots, with a full-length cash compartment between them.',
      defaults: { dimensions_cm: { length: 11, width: 2, height: 9 }, front_slots: 3, back_slots: 3, cash_compartments: 2 },
      labor_factor: 1,
    },
    {
      id: 'PASSPORT_COVER',
      label: 'Passport cover',
      detect: /passport|paspor/i,
      vision_cue: 'Book-like cover sized for a passport (about 10 x 14 cm closed) with sleeves inside the covers.',
      defaults: { dimensions_cm: { length: 10, width: 1, height: 14 }, front_slots: 2, back_slots: 0 },
      labor_factor: 0.8,
    },
    {
      id: 'KEY_POUCH',
      label: 'Key pouch / key holder',
      detect: /key ?(pouch|holder|case)|gantungan kunci|tempat kunci/i,
      vision_cue: 'Small pouch or fold with a key ring or hooks inside.',
      defaults: { dimensions_cm: { length: 7, width: 1.5, height: 11 } },
      labor_factor: 0.5,
    },
    {
      id: 'OTHER_SMALL_GOODS',
      label: 'Other small good',
      detect: /(?!)/,
      vision_cue: 'Any other small leather good.',
      defaults: {},
      labor_factor: 0.8,
    },
  ],
  fields: {
    dimensions_cm: dimensionsField('Closed size. A flat card holder is usually ~10 x 7 cm. Two numbers = length x height.'),
    exterior_leather: leatherField(),
    color: {
      type: 'text',
      label: 'Color',
      label_id: 'Warna',
      group: 'material',
      description: 'Leather color as the client calls it, e.g. "hitam", "biru tosca".',
      parse: parseColor,
    },
    front_slots: {
      type: 'number', zone: 'interior',
      label: 'Front card slots',
      label_id: 'Slot kartu depan',
      group: 'layout',
      description: 'Card slots on the front face (flat card holders) or the left half (wallets). Split the client total between front and back.',
      parse: (t) => {
        const n = cards(t);
        return n ? Math.ceil(n / 2) : undefined;
      },
    },
    back_slots: {
      type: 'number', zone: 'interior',
      label: 'Back card slots',
      label_id: 'Slot kartu belakang',
      group: 'layout',
      description: 'Card slots on the back face / right half.',
      parse: (t) => {
        const n = cards(t);
        return n ? Math.floor(n / 2) : undefined;
      },
    },
    central_pockets: {
      type: 'number', zone: 'interior',
      label: 'Central pocket',
      label_id: 'Kantong tengah',
      group: 'layout',
      description: 'Pocket between front and back slots for folded cash ("selipan uang di tengah" = 1).',
      parse: (t) => (/selipan uang|uang tunai|kantong tengah|saku tengah|pocket tengah/i.test(t) && !/slot\s*uang/i.test(t) ? 1 : undefined),
    },
    cash_compartments: {
      type: 'number', zone: 'interior',
      label: 'Cash compartments',
      label_id: 'Kompartemen uang',
      group: 'layout',
      description: 'Full-length bill compartments (bifold / long wallets).',
      parse: (t) => parseCount(t, 'slot uang|kompartemen uang|ruang uang|cash'),
    },
    id_window: {
      type: 'boolean', zone: 'interior',
      label: 'ID / photo window',
      label_id: 'Jendela ID/foto',
      group: 'layout',
      description: 'Transparent window for an ID card or photo.',
      parse: (t) => (/mika|foto transparan|id window|jendela|window/i.test(t) ? true : undefined),
    },
    coin_zip_pocket: {
      type: 'boolean', zone: 'interior',
      label: 'Coin zip pocket',
      label_id: 'Saku koin ber-zipper',
      group: 'layout',
      description: 'Zippered coin pocket.',
      parse: (t) => (/koin.{0,25}(zip|sleting)|(zip|sleting).{0,25}koin/i.test(t) ? true : undefined),
    },
    zipper: {
      type: 'text',
      label: 'Zipper',
      label_id: 'Sleting',
      group: 'construction',
      placeholder: 'e.g. YKK Excella Gold #5',
      description: 'Zipper brand / color. Only for zip-around wallets or coin zip pockets.',
      parse: parseZipper,
      relevant: hasZip,
    },
    lining: {
      type: 'text', zone: 'interior',
      label: 'Lining',
      label_id: 'Lining',
      group: 'material',
      description: 'Interior lining material, or "Tanpa lining".',
      parse: parseLining,
    },
    edge_finish: leatherEdgeField(),
    stitching_method: stitchingMethodField(),
    stitch_pattern: {
      type: 'text',
      label: 'Stitch pattern',
      label_id: 'Pola jahitan',
      group: 'finish',
      description: 'e.g. "diamond stitch".',
      parse: parseStitchPattern,
    },
    thread_material: {
      type: 'text',
      label: 'Thread material',
      label_id: 'Bahan benang',
      group: 'finish',
      description: 'e.g. "linen", "waxed polyester".',
      parse: parseThreadMaterial,
    },
    thread_color: threadColorField(),
    ...embossingFields<SmallGoodsAttributes>(),
  },
  topics: [
    { id: 'construction', label: 'Model', ask: 'mau yang tipis khusus kartu, model lipat biasa yang muat uang kertas, atau dompet panjang pakai resleting', required: true, fields: [], deferrable: false, is_filled: (s) => s.construction_type !== 'UNSPECIFIED' },
    { id: 'size', label: 'Ukuran', ask: 'biasanya dompetnya disimpan di saku celana atau di tas', required: true, fields: ['dimensions_cm'], deferrable: true },
    { id: 'material', label: 'Kulit', ask: 'lebih suka kulit yang makin lama warnanya makin cantik (kesan vintage), atau yang tahan gores dan bentuknya tetap rapi, dan warnanya mau apa', required: true, fields: ['exterior_leather'], deferrable: false },
    {
      id: 'layout',
      label: 'Slot kartu',
      ask: 'biasanya bawa berapa kartu, dan perlu tempat uang kertas juga',
      required: true,
      fields: ['front_slots', 'back_slots', 'central_pockets', 'cash_compartments'],
      applies_to: [...WALLETS],
      deferrable: true,
    },
    { id: 'personalization', label: 'Emboss', ask: 'mau ditambah inisial nama atau logo di bagian luarnya', required: false, fields: ['embossing_type'], deferrable: true },
    { id: 'zipper', label: 'Sleting', ask: 'aksesoris logam resletingnya mau warna emas, silver, atau hitam', required: false, fields: ['zipper'], applies_to: ['ZIP_AROUND_LONG_WALLET'], deferrable: true },
    { id: 'edge', label: 'Pinggiran', ask: 'pinggiran kulitnya mau dibuat licin mengkilap, dicat rapi senada, atau dibiarkan natural', required: false, fields: ['edge_finish'], deferrable: true },
    { id: 'thread', label: 'Benang', ask: 'jahitannya mau warna senada biar halus, atau kontras biar kelihatan', required: false, fields: ['thread_color', 'thread_material'], deferrable: true },
    { id: 'lining', label: 'Lining', ask: 'bagian dalamnya mau dilapis bahan halus, atau dibiarkan kulit polos biar lebih tipis', required: false, fields: ['lining'], applies_to: ['BIFOLD_WALLET', 'TRIFOLD_WALLET', 'ACCORDION_WALLET', 'ZIP_AROUND_LONG_WALLET', 'PASSPORT_COVER'], deferrable: true },
  ],
};
